# Generated by Django 2.2 on 2019-04-29 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('imagen_conductor', models.ImageField(upload_to='static/img/images_conductores/')),
                ('numero_certificado', models.TextField(max_length=30)),
                ('numero_celular', models.CharField(max_length=30)),
                ('raiting', models.CharField(max_length=30)),
                ('placa_carro', models.CharField(max_length=30)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 69153))),
            ],
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('imagen_cupon', models.ImageField(upload_to='static/img/images_cupones/')),
                ('descripcion', models.TextField(max_length=30)),
                ('porcentaje_descuento', models.CharField(max_length=30)),
                ('descuento_plano', models.CharField(max_length=30)),
                ('inicio', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 67340))),
                ('expiration', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 67389))),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 67423))),
            ],
        ),
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('imagen_pasajero', models.ImageField(upload_to='static/img/images_pasajeros/')),
                ('numero_certificado', models.TextField(max_length=30)),
                ('numero_celular', models.CharField(max_length=30)),
                ('balance', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 70855))),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('imagen_promocion', models.ImageField(upload_to='static/img/images_promociones/')),
                ('inicio', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 74309))),
                ('fin', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 74367))),
                ('descripcion', models.TextField(max_length=30)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 74430))),
            ],
        ),
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('de', models.CharField(max_length=30)),
                ('tipo', models.TextField(max_length=30)),
                ('tema', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=30)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 64706))),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_de_llamadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=30)),
                ('porcentaje_descuento', models.CharField(max_length=30)),
                ('descuento_plano', models.CharField(max_length=30)),
                ('inicio', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 61725))),
                ('expiration', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 61781))),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 61818))),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_de_pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=30)),
                ('numero_conductor', models.CharField(max_length=30)),
                ('fecha_solicitud', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 65759))),
                ('fecha_pago', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 65812))),
                ('monto', models.CharField(max_length=30)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('comentario', models.TextField(max_length=5000)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 65937))),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_inicio', models.CharField(max_length=3000)),
                ('direccion_destino', models.CharField(max_length=3000)),
                ('raiting', models.TextField(max_length=30)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 4, 29, 21, 25, 31, 75824))),
            ],
        ),
    ]
